export const INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR";
export const BAD_REQUEST_ERROR = "BAD REQUEST";
export const NOT_FOUND_ERROR = "NOT FOUND";
export const UNAUTHORIZED_ERROR = "UNAUTHORIZED ACCESS";
export const FORBIDDEN_ERROR = "FORBIDDEN RESOURCE";
export const CONFLICT_ERROR = "CONFLICT, ALREADY EXISTS";
export const UNPROCESSABLE_ENTITY_ERROR = "UNPROCESSABLE ENTITY";
